name: nextjs-collaboration

services:
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      # - /app/.next
      - /dev/null:/app/nextjs_mongo.log # Added to prevent cache thrashing
    environment:
      - MONGO_URI=${MONGO_URI}
      - WATCHPACK_POLLING=true
    deploy:
      resources:
        limits:
          memory: 4G
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

  y-server:
    build: .
    container_name: yjs_broadcaster
    ports:
      - '1234:1234'
    volumes:
      - .:/app
      - /app/
    environment:
      - MONGO_URI=${MONGO_URI}
      - WATCHPACK_POLLING=true
    command: ['npm', 'run', 'y-server']
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: nextjs_mongo
    hostname: ${MONGO_HOST}
    # ports:
    # - '27018:27017' # 27018 for Compass (Windows) | 27017 for App (Internal)
    volumes:
      - nextjs_mongo_data:/data/db
    networks:
      - app-network
    command: >
      bash -c "
      mongod --replSet rs0 --bind_ip_all --logpath /dev/null & 
      until mongosh --eval 'db.adminCommand(\"ping\")' &>/dev/null; do sleep 2; done;
      mongosh --eval 'try { rs.initiate({_id:\"rs0\", members:[{_id:0, host:\"mongodb:27017\"}]}); } catch (e) { if (e.codeName !== \"AlreadyInitialized\") throw e; }';
      wait
      "
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # Dashboard
  mongo-express:
    image: mongo-express:latest
    container_name: nextjs_mongo_express
    restart: unless-stopped
    ports:
      - '8081:8081' # Access via http://localhost:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/example?replicaSet=rs0
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nextjs_mongo_data:
    name: nextjs_mongo_data
  next_cache:
    name: next_cache
